apiVersion: v1
kind: Service
metadata:
  name: llm-api-service
  namespace: llm-serving
  labels:
    app: llm-api
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: llm-api